#version 450

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform Parameters
{
    uint index;
} parameters;

layout(set = 0, binding = 0, std430) readonly buffer Input
{
    uint values[];
} input_data;

layout(set = 0, binding = 1, std430) buffer Output
{
    uint value;
} output_data;

void main()
{
    output_data.value = input_data.values[parameters.index];
}
