#version 450

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba8) uniform readonly image2D input_image;

layout(set = 0, binding = 1, std430) buffer Output
{
    uint value;
} output_data;

void main()
{
    vec4 value = imageLoad(input_image, ivec2(100, 100));
    output_data.value = uint(round(value.r * 255.0)) |
                        (uint(round(value.g * 255.0)) << 8) |
                        (uint(round(value.b * 255.0)) << 16) |
                        (uint(round(value.a * 255.0)) << 24);
}
